### 로그아웃 테스트

GET http://localhost:8080/auth/logout
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiTXVybXVyIGFwcCIsImlhdCI6MTY5MDI2MDg3NSwiZXhwIjoxNjkwMjYwODk1fQ.LSDrj4x8f9mFRSKUBs7RtMLHzFV14xn14azWeY2U8pI

### 토근 정상 동작 요청 - Authentication 변경하면서 사용해야함.

GET http://localhost:8080/posts/1
Accept: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoiTXVybXVyIGFwcCIsImlhdCI6MTY5MDI2MDg3NSwiZXhwIjoxNjkwMjYwODk1fQ.LSDrj4x8f9mFRSKUBs7RtMLHzFV14xn14azWeY2U8pI

### 로그인 요청

POST http://localhost:8080/auth/login
Content-Type: application/json;charset=UTF-8

{"email":"genug@gmail.com","password":"qA^12345"}

### 테스트에 사용할 임시 계정 생성

POST http://localhost:8080/auth/signup
Content-Type: application/json;charset=UTF-8



